### ISSUE TITLE
I had to manually install `pry` to get it to work

### ISSUE THREAD

**Issue by benski** [jmmastey/bundler-stats#16]
```
 ✘ benallison@grey-beast  ~/ihr/ios-flagship   develop ●  bundle-stats help
Traceback (most recent call last):
	14: from /Users/benallison/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	13: from /Users/benallison/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	12: from /Users/benallison/.rvm/gems/ruby-2.6.3/bin/bundle-stats:23:in `<main>'
	11: from /Users/benallison/.rvm/gems/ruby-2.6.3/bin/bundle-stats:23:in `load'
	10: from /Users/benallison/.rvm/gems/ruby-2.6.3/gems/bundler-stats-1.1.0/bin/bundle-stats:9:in `<top (required)>'
	 9: from /Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Users/benallison/.rvm/gems/ruby-2.6.3/gems/bundler-stats-1.1.0/lib/bundler/stats/cli.rb:5:in `<top (required)>'
	 6: from /Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /Users/benallison/.rvm/gems/ruby-2.6.3/gems/bundler-stats-1.1.0/lib/bundler/stats.rb:2:in `<top (required)>'
	 3: from /Users/benallison/.rvm/gems/ruby-2.6.3/gems/bundler-stats-1.1.0/lib/bundler/stats.rb:2:in `require_relative'
	 2: from /Users/benallison/.rvm/gems/ruby-2.6.3/gems/bundler-stats-1.1.0/lib/bundler/stats/tree.rb:1:in `<top (required)>'
	 1: from /Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/benallison/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
 ✘ benallison@grey-beast  ~/ihr/ios-flagship   develop ●  gem install pry
Fetching method_source-1.0.0.gem
Fetching coderay-1.1.3.gem
Fetching pry-0.13.1.gem
Successfully installed coderay-1.1.3
Successfully installed method_source-1.0.0
Successfully installed pry-0.13.1
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.3
Installing ri documentation for coderay-1.1.3
Parsing documentation for method_source-1.0.0
Installing ri documentation for method_source-1.0.0
Parsing documentation for pry-0.13.1
Installing ri documentation for pry-0.13.1
Done installing documentation for coderay, method_source, pry after 1 seconds
3 gems installed
 benallison@grey-beast  ~/ihr/ios-flagship   develop ●  bundle-stats help
Commands:
  bundle-stats help [COMMAND]   # Describe available commands or one specific command
  bundle-stats show TARGET      # Prints the dependency tree for a single gem in your Gemfile
  bundle-stats stats            # Displays basic stats about the gems in your Gemfile
  bundle-stats version          # Prints the bundler-stats version
  bundle-stats versions TARGET  # Shows versions requirements for target in other dependencies

```

**Comment by jhirbour** [comment]
🤔 https://github.com/jmmastey/bundler-stats/blob/master/bundler-stats.gemspec#L44

**Comment by jmmastey** [comment]
Sorry about that! Could you try updating to `2.0.1`? Looks like I fixed this in a release since then.

**Comment by jmmastey** [comment]
I'm going to close this for now. If you run into the same problem in 2.0.1, feel free to reopen.
